### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by cyqsimon** [kepi/ssh-fingerprints#1]
Hello,

Thanks for the script. I found it very useful.

I would like to package this script on COPR and AUR to make installing it easier. Can you please consider adding a tag (something like `v0.2`) so that I have a predictable source URL to work with?

Thanks in advance.

**Comment by kepi** [comment]
Hello,

sure, tags are in place. Thanks for the effort. PR with updated install instructions is definitely welcomed.

Cheers
